src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'quiz.views.error_404'
handler500 = 'quiz.views.error_500'
handler403 = 'quiz.views.error_403'
handler400 = 'quiz.views.error_400'

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultCreateView, TestResultQuestionUpdateView, \
    TestResultDetailView, TestResultUpdateView, RatingDetailView, DeleteResultView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('rating/', RatingDetailView.as_view(), name='rating'),
    path('<uuid:uuid>/results/create', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details', TestResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete', DeleteResultView.as_view(), name='result_delete'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next',
         TestResultQuestionUpdateView.as_view(),
         name='question'),
]

src/quiz/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from accounts.models import User
from core.models import BaseModel

# Create your models here.
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def __str__(self):
        return f'{self.title}'

    def questions_count(self):
        return self.questions.count()

    def _get_best_result(self):
        if not self.results.all():
            return {'score': 'N/A', 'user': 'N/A'}
        result = self.results.first()
        for temp_result in self.results.all():
            if temp_result.num_incorrect_answers < result.num_incorrect_answers:
                result = temp_result
            elif temp_result.num_incorrect_answers == result.num_incorrect_answers:
                if temp_result.get_elapsed_time() < result.get_elapsed_time():
                    result = temp_result
        return {'score': result.num_correct_answers, 'user': result.user}

    def get_best_result_score(self):
        return self._get_best_result()['score']

    def get_best_result_user(self):
        return self._get_best_result()['user']

    def get_time_last_run(self):
        if self.results.last():
            return self.results.last().create_date
        return 'First start'

    def has_unfinished_run(self):
        return self.results.exclude(
            state=Result.STATE.FINISHED
        ).exists()

    @property
    def current_run(self):
        return self.results.exclude(
            state=Result.STATE.FINISHED
        ).first()


class Question(models.Model):
    ANSWER_MIN_LIMIT = 1
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def is_last(self, order_number):
        return order_number == self.test.questions_count()

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    current_order_number = models.PositiveSmallIntegerField(null=True)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def __str__(self):
        return f'{self.test} = {self.get_points()}'

    def get_elapsed_time(self):
        a = self.write_date
        b = self.create_date
        return self.write_date - self.create_date

    def get_points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def get_success_rate(self):
        return self.num_correct_answers/self.test.questions_count()*100

    def update_result(self, order_number, question, selected_choices):
        choices = question.choices.all()

        correct_answer = int(all(
            selected_choice == choices[i].is_correct
            for i, selected_choice in enumerate(selected_choices)
        ))

        self.num_correct_answers += correct_answer
        self.num_incorrect_answers += 1 - correct_answer
        self.current_order_number = question.order_number
        if question.is_last(order_number):
            self.state = self.STATE.FINISHED
        self.save()

    def save(self, *args, **kwargs):
        if self.state == self.STATE.FINISHED:
            self.user.rating += self.get_points()
            self.user.save()
        super().save(*args, **kwargs)

src/quiz/forms.py
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, modelformset_factory, ModelForm
from django import forms
from quiz.models import Choice


class QuestionsInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Quantity of questions is out of range ({}..{})'.format(
                self.instance.QUESTION_MIN_LIMIT, self.instance.QUESTION_MAX_LIMIT
            ))

        order_numbers = [question['order_number'] for question in self.cleaned_data]
        order_numbers.sort()
        order_numbers_correct_sequence = list(range(1, len(self.forms)+1))
        if order_numbers != order_numbers_correct_sequence:
            raise ValidationError('The order number must start with 1 and have no gaps')


class ChoiceInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.ANSWER_MIN_LIMIT <= len(self.forms) <= self.instance.ANSWER_MAX_LIMIT):
            raise ValidationError('Quantity of answers is out of range ({}..{})'.format(
                self.instance.ANSWER_MIN_LIMIT, self.instance.ANSWER_MAX_LIMIT
            ))

        total_number = sum(
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        )

        if total_number == len(self.forms):
            raise ValidationError('NOT allowed to select all choices')

        if total_number == 0:
            raise ValidationError('At LEAST 1 choice should be selected')


class ChoiceForm(ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Choice
        fields = ['text']



    # def __init__(self, **kwargs):
    #     super().__init__(**kwargs)
    # self.fields['text'].widget = HiddenInput()


ChoiceFormSet = modelformset_factory(
    model=Choice,
    form=ChoiceForm,
    extra=0
)

src/quiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render  # noqa
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accounts.models import User
from quiz.forms import ChoiceFormSet
from quiz.models import Test, Result, Question


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 'quiz/list.html'
    context_object_name = 'tests'


class TestDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Test
    template_name = 'quiz/details.html'
    context_object_name = 'test'
    pk_url_kwarg = 'uuid'
    paginate_by = 2

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        return context

    def get_queryset(self):
        return Result.objects.filter(
            test=self.get_object(),
            user=self.request.user
        )


class TestResultCreateView(LoginRequiredMixin, CreateView):

    def post(self, request, uuid):
        result = Result.objects.create(
            test=Test.objects.get(uuid=uuid),
            user=request.user,
            state=Result.STATE.NEW,
            current_order_number=0,
        )
        result.save()

        return HttpResponseRedirect(reverse(
            'tests:question',
            kwargs={
                'uuid': uuid,
                'result_uuid': result.uuid,
                # 'order_number': 1
            }
        ))


class TestResultDetailView(LoginRequiredMixin, DetailView):
    model = Result
    template_name = 'results/details.html'
    context_object_name = 'result'

    def get_object(self):
        uuid = self.kwargs.get('result_uuid')
        return self.get_queryset().get(uuid=uuid)


class TestResultQuestionUpdateView(LoginRequiredMixin, UpdateView):

    def get(self, request, uuid, result_uuid):

        order_number = Result.objects.get(uuid=result_uuid).current_order_number + 1

        question = Question.objects.get(
            test__uuid=uuid,
            order_number=order_number
        )

        choices = ChoiceFormSet(queryset=question.choices.all())

        return render(
            request=request,
            template_name='quiz/questions.html',
            context={
                'question': question,
                'choices': choices
            }
        )

    def post(self, request, uuid, result_uuid):

        order_number = Result.objects.get(uuid=result_uuid).current_order_number + 1

        question = Question.objects.get(
            test__uuid=uuid,
            order_number=order_number
        )

        choices = ChoiceFormSet(data=request.POST)
        selected_choices = [
            'is_selected' in form.changed_data
            for form in choices.forms
        ]

        result = Result.objects.get(
            uuid=result_uuid
        )

        if len(set(selected_choices)) == 1:
            messages.error(self.request, "All false or all true")
            return HttpResponseRedirect(reverse(
                'tests:question',
                kwargs={
                    'uuid': uuid,
                    'result_uuid': result.uuid,
                    # 'order_number': order_number+1
                }
            ))

        result.update_result(order_number, question, selected_choices)

        if result.state == Result.STATE.FINISHED:
            return HttpResponseRedirect(reverse(
                'tests:result_details',
                kwargs={
                    'uuid': uuid,
                    'result_uuid': result.uuid,
                }
            ))
        else:
            return HttpResponseRedirect(reverse(
                'tests:question',
                kwargs={
                    'uuid': uuid,
                    'result_uuid': result.uuid,
                    # 'order_number': order_number+1
                }
            ))


class TestResultUpdateView(LoginRequiredMixin, UpdateView):
    def get(self, request, uuid, result_uuid):
        return HttpResponseRedirect(reverse(
            'tests:question',
            kwargs={
                'uuid': uuid,
                'result_uuid': result_uuid,
                # 'order_number': result.current_order_number+1
            }
        ))


class RatingDetailView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'results/rating.html'


class DeleteResultView(LoginRequiredMixin, DeleteView):
    model = Result
    template_name = 'results/delete.html'
    pk_url_kwarg = 'result_uuid'
    success_url = reverse_lazy('tests:list')

    def get_object(self):
        uuid = self.kwargs.get('result_uuid')
        return self.model.objects.get(uuid=uuid)


def error_404(request, *args, **argv):
    return render(request, '404.html', status=404)


def error_500(request, *args, **argv):
    return render(request, '500.html', status=500)


def error_400(request, *args, **argv):
    return render(request, '400.html', status=400)


def error_403(request, *args, **argv):
    return render(request, '403.html', status=403)

src/quiz/templates/quiz/details.html
{% extends 'base.html' %}

{% block title %}
    <h1>{{ test }}</h1>
{% endblock %}

{% block main %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Test info</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Description</td>
                        <td>{{ test.description }}</td>
                      </tr>
                      <tr>
                        <td>Num of questions</td>
                        <td>{{ test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Num of runs</td>
                        <td>{{ test.results.count }}</td>
                      </tr>
                      <tr>
                        <td>Best result</td>
                        <td> {{ test.get_best_result_score }} (user: {{ test.get_best_result_user }})</td>
                      </tr>
                      <tr>
                        <td>Last run</td>
                        <td>{{ test.get_time_last_run }}</td>
                      </tr>
                      <tr>
                        <td>Current open test result</td>
                        <td>N/A</td>
                      </tr>
                    </tbody>
                  </table>
            </div>

            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{{ test.image.url }}">
                </div>
                <form action="{% url 'tests:result_create' test.uuid %}" method="post" class="d-flex justify-content-center mt-5 mb-5" >
                    {% csrf_token %}
                    <input type="submit" class="btn-lg btn-success" value="START ▶️">
                </form>

{#                {% if continue_flag %}#}
{#                    <div class="d-flex justify-content-center mt-5 mb-5" >#}
{#                            <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-warning">CONTINUE ▶️</a>#}
{#                    </div>#}
{#                {% else %}#}
{#                    <div class="d-flex justify-content-center mt-5 mb-5" >#}
{#                        <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>#}
{#                    </div>#}
{#                {% endif %}#}
            </div>
            <table class="table table-striped table-hover" autocomplete="off">
              <tr>
                <th>#</th>
                <th>Create date</th>
                <th>Write date</th>
                <th>User</th>
                <th>Points</th>
                <th>State</th>
                <th>Actions</th>
              </tr>
                {% for result in object_list %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ result.create_date }}</td>
                        <td>{{ result.write_date }}</td>
                        <td>{{ result.user }}</td>
                        <td>{{ result.get_points }}</td>
                        <td>{{ result.get_state_display }}</td>
                        <td>
                            {% if result.state == result.STATE.NEW %}
                                <a href="{% url 'tests:result_update' test.uuid result.uuid %}" class="btn-lg btn-warning">CONTINUE</a>
                                <a href="{% url 'tests:result_delete' test.uuid result.uuid %}" class="btn-lg btn-danger">DELETE</a>
                            {% else %}
                                <a href="{% url 'tests:result_delete' test.uuid result.uuid %}" class="btn-lg btn-danger">DELETE</a>
                            {% endif %}
                        </td>
                      </tr>
                {% endfor %}
            </table>
            <div class="p-1 m-1">
                {% include 'includes/paginator.html' %}
            </div>

{##}
{#        <table class="table table-hover" style="width:100%">#}
{#            <thead class="thead-dark">#}
{#            <tr>#}
{#                <th>#</th>#}
{#                <th>User</th>#}
{#                <th>Started</th>#}
{#                <th>Time spent</th>#}
{#                <th>Points</th>#}
{#            </tr>#}
{#            </thead>#}
{##}
{#            {% for result in test.test_results.all %}#}
{#            {% for result in test_results %}#}
{##}
{#                <tr>#}
{#                   <td>{{ forloop.counter}}</td>#}
{#                   <td>{{ result.user.username }}</td>#}
{#                   <td>{{ result.write_date }}</td>#}
{#                   <td>{{ result.time_spent }}</td>#}
{#                   <td>{{ result.points }}</td>#}
{#                </tr>#}
{##}
{#            {% endfor %}#}
{#        </table>#}

        </div>
    </div>

{% endblock %}

src/quiz/templates/quiz/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <h1>Test list</h1>
{% endblock %}

{% block main %}
    {% if tests %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                  <th></th>
                  <th>Titlwq12we</th>
                  <th>Description</th>
{#                  <th>Level</th>#}
                  <th></th>
                </tr>
            </thead>

            {% for test in tests %}
                <tr>
                    <td><img class="rounded-circle p-1 m-1" width="150" height="150"  src="{{ test.image.url }}"></td>
                    <td> {{ test.title }}</td>
                    <td> {{ test.description }}</td>
{#                    <td> {{ test.get_level_display }}</td>#}
{#                    <td> <img src="{% static 'testify/levels/' %}{{ test.get_level_display }}.png" height="30px" width="40px"/> </td>#}
                    <td> <a href="{% url 'tests:details' uuid=test.uuid %}">DETAILS</a></td>
                </tr>
            {% endfor %}
        </table>

        <div class="p-1 m-1">
            {% include 'includes/paginator.html' %}
        </div>
    {% else %}
        <p>No tests yet :(</p>
    {% endif %}

{% endblock %}

src/quiz/templates/quiz/questions.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}
{#{% load math_funcs %}#}

{% block title %}
    <h1>Question: {{ question.text }}?</h1>
    {% with question.order_number|add:-1|div:question.test.questions_count|mult:100  as progress_level %}
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: {{ progress_level }}%" aria-valuenow="{{ progress_level }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
{% endwith %}
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}

        {{choices.management_form}}

        <div class="border-buttom mb-3">
            Please, select one of the possible choices below:
        </div>

        {% for form in choices %}

            <div class="mt-1">

                {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}"> {{ form.text.value }}</label>

            </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">Next</button>
    </form>
{% endblock %}