src/accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'quiz.views.error_404'
handler500 = 'quiz.views.error_500'
handler403 = 'quiz.views.error_403'
handler400 = 'quiz.views.error_400'

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultCreateView, TestResultQuestionUpdateView, \
    TestResultDetailView, TestResultUpdateView, RatingDetailView, DeleteResultView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('rating/', RatingDetailView.as_view(), name='rating'),
    path('<uuid:uuid>/results/create', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details', TestResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete', DeleteResultView.as_view(), name='result_delete'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next',
         TestResultQuestionUpdateView.as_view(),
         name='question'),
]

src/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="{% static 'quiz/css/style.css' %}" rel="stylesheet" />
    <title>Quiz11</title>
</head>
<body>
<section class="header">
    <div class="container menu__container header-menu">
        <div class="menu">
            <a href="/" class="menu__logo"><img src="{% static 'quiz/img/logo.png' %}" alt="logo"></a>
            <ul class="menu__list">
                <li class="menu__item"><a href="{% url 'tests:list' %}">Quiz</a></li>
                <li class="menu__item"><a href="{% url 'tests:rating' %}">Rating</a></li>
                {% if user.is_authenticated %}
                <li class="menu__item"><a href="{% url 'accounts:profile' %}"><img src="{{ user.image.url }}" alt="" width="40px">Profile  {{ user.username }}</a></li>
                <li class="menu__item"><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li class="menu__item"><a href="{% url 'accounts:login' %}">Sign in</a></li>
                <li class="menu__item"><a href="{% url 'accounts:registration' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</section>
<section class="container">
    {% include 'includes/messages.html' %}
    {% block title%}
    {% endblock %}
    {% block main%}
    {% endblock %}
</section>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% endblock %}